$(document).ready(function() {
  $('#Cb-color-fuchsia').on('change', function () {
    if ($('#Cb-color-fuchsia').is(':checked')) {
        $('.A .vert').css('background', 'fuchsia');
        $('.A .hor1').css('background', 'fuchsia');
        $('.A .hor2').css('background', 'fuchsia');
        $('.A .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.A .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.B .vert').css('background', 'fuchsia');
        $('.B .hor1').css('background', 'fuchsia');
        $('.B .hor2').css('background', 'fuchsia');
        $('.B .tr1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.B .tr2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.C .vert').css('background', 'fuchsia');
        $('.C .hor1').css('background', 'fuchsia');
        $('.C .hor2').css('background', 'fuchsia');
        $('.C .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.D .vert1').css('background', 'fuchsia');
        $('.D .vert2').css('background', 'fuchsia');
        $('.D .hor1').css('background', 'fuchsia');
        $('.D .hor2').css('background', 'fuchsia');
        $('.D .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.E .vert').css('background', 'fuchsia');
        $('.E .hor1').css('background', 'fuchsia');
        $('.E .hor2').css('background', 'fuchsia');
        $('.E .hor3').css('background', 'fuchsia');
        $('.E .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.F .vert').css('background', 'fuchsia');
        $('.F .hor1').css('background', 'fuchsia');
        $('.F .hor2').css('background', 'fuchsia');
        $('.F .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.G .vert').css('background', 'fuchsia');
        $('.G .hor1').css('background', 'fuchsia');
        $('.G .hor2').css('background', 'fuchsia');
        $('.G .hor3').css('background', 'fuchsia');
        $('.G .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.G .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.H .vert1').css('background', 'fuchsia');
        $('.H .vert2').css('background', 'fuchsia');
        $('.H .hor1').css('background', 'fuchsia');
        $('.H .hor2').css('background', 'fuchsia');
        $('.H .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.I .vert').css('background', 'fuchsia');
        $('.I .hor1').css('background', 'fuchsia');
        $('.I .hor2').css('background', 'fuchsia');
        $('.I .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.I .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.J .vert').css('background', 'fuchsia');
        $('.J .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.J .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.K .vert').css('background', 'fuchsia');
        $('.K .hor').css('background', 'fuchsia');
        $('.K .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.K .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.L .vert').css('background', 'fuchsia');
        $('.L .hor').css('background', 'fuchsia');
        $('.L .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.M .vert1').css('background', 'fuchsia');
        $('.M .vert2').css('background', 'fuchsia');
        $('.M .vert3').css('background', 'fuchsia');
        $('.M .tr1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.M .tr2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.N .vert1').css('background', 'fuchsia');
        $('.N .vert2').css('background', 'fuchsia');
        $('.N .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.N .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.O .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.O .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.O .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.O .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.P .vert').css('background', 'fuchsia');
        $('.P .hor1').css('background', 'fuchsia');
        $('.P .hor2').css('background', 'fuchsia');
        $('.P .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.Q .hor').css('background', 'fuchsia');
        $('.Q .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.Q .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.Q .bl1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.Q .bl2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.Q .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.R .vert').css('background', 'fuchsia');
        $('.R .hor1').css('background', 'fuchsia');
        $('.R .hor2').css('background', 'fuchsia');
        $('.R .hor3').css('background', 'fuchsia');
        $('.R .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.R .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.S .hor1').css('background', 'fuchsia');
        $('.S .hor2').css('background', 'fuchsia');
        $('.S .hor3').css('background', 'fuchsia');
        $('.S .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.S .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.T .vert').css('background', 'fuchsia');
        $('.T .hor1').css('background', 'fuchsia');
        $('.T .hor2').css('background', 'fuchsia');
        $('.T .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.U .vert1').css('background', 'fuchsia');
        $('.U .vert2').css('background', 'fuchsia');
        $('.U .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.U .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.V .vert1').css('background', 'fuchsia');
        $('.V .vert2').css('background', 'fuchsia');
        $('.V .hor').css('background', 'fuchsia');
        $('.V .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.W .vert1').css('background', 'fuchsia');
        $('.W .vert2').css('background', 'fuchsia');
        $('.W .vert3').css('background', 'fuchsia');
        $('.W .br1').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.W .br2').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.X .vert1').css('background', 'fuchsia');
        $('.X .vert2').css('background', 'fuchsia');
        $('.X .vert3').css('background', 'fuchsia');
        $('.X .vert4').css('background', 'fuchsia');
        $('.X .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.X .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.X .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.X .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.Y .vert1').css('background', 'fuchsia');
        $('.Y .vert2').css('background', 'fuchsia');
        $('.Y .hor1').css('background', 'fuchsia');
        $('.Y .hor2').css('background', 'fuchsia');
        $('.Y .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.Y .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.Z .hor1').css('background', 'fuchsia');
        $('.Z .hor2').css('background', 'fuchsia');
        $('.Z .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.Z .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.one .vert').css('background', 'fuchsia');
        $('.one .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.two .hor1').css('background', 'fuchsia');
        $('.two .hor2').css('background', 'fuchsia');
        $('.two .tl1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.two .tl2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.two .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.three .hor1').css('background', 'fuchsia');
        $('.three .hor2').css('background', 'fuchsia');
        $('.three .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.three .tr1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.three .tr2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.four .vert1').css('background', 'fuchsia');
        $('.four .vert2').css('background', 'fuchsia');
        $('.four .hor').css('background', 'fuchsia');
        $('.four .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.five .hor1').css('background', 'fuchsia');
        $('.five .hor2').css('background', 'fuchsia');
        $('.five .hor3').css('background', 'fuchsia');
        $('.five .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.five .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.six .hor1').css('background', 'fuchsia');
        $('.six .hor2').css('background', 'fuchsia');
        $('.six .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.six .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.six .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.seven .vert').css('background', 'fuchsia');
        $('.seven .hor').css('background', 'fuchsia');
        $('.seven .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.eight .hor1').css('background', 'fuchsia');
        $('.eight .hor2').css('background', 'fuchsia');
        $('.eight .tl1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.eight .tl2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.eight .tr1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.eight .tr2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.nine .hor1').css('background', 'fuchsia');
        $('.nine .hor2').css('background', 'fuchsia');
        $('.nine .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.nine .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.nine .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.zero .hor').css('background', 'fuchsia');
        $('.zero .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.zero .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.zero .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.zero .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.exclamation .vert').css('background', 'fuchsia');
        $('.exclamation .circ').css('border', '5px solid fuchsia');
        $('.question .vert').css('background', 'fuchsia');
        $('.question .hor').css('background', 'fuchsia');
        $('.question .top').css({'border':'5px solid fuchsia','border-bottom':'none'});
        $('.question .circ').css('border', '5px solid fuchsia');
        $('.period .circ').css('border', '5px solid fuchsia');
        $('.comma .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.colon .circ1').css('border', '5px solid fuchsia');
        $('.colon .circ2').css('border', '5px solid fuchsia');
        $('.semicolon .circ').css('border', '5px solid fuchsia');
        $('.semicolon .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.singlequotel .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.singlequoter .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.doublequotel .tl1').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.doublequotel .tl2').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.doublequoter .br1').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.doublequoter .br2').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.dash .hor').css('background', 'fuchsia');
        $('.parenthesisl .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.parenthesisl .bl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.parenthesisr .tr').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.parenthesisr .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.plus .vert').css('background', 'fuchsia');
        $('.plus .hor').css('background', 'fuchsia');
        $('.equal .hor1').css('background', 'fuchsia');
        $('.equal .hor2').css('background', 'fuchsia');
        $('.slash .hor1').css('background', 'fuchsia');
        $('.slash .hor2').css('background', 'fuchsia');
        $('.slash .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
        $('.slash .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.dollar .vert').css('background', 'fuchsia');
        $('.dollar .hor1').css('background', 'fuchsia');
        $('.dollar .hor2').css('background', 'fuchsia');
        $('.dollar .hor3').css('background', 'fuchsia');
        $('.dollar .br').css({'border':'5px solid fuchsia','border-top':'none','border-left':'none'});
        $('.dollar .tl').css({'border':'5px solid fuchsia','border-bottom':'none','border-right':'none'});
    }
  });
});